// import './themes/themes.scss'
// import './test/test.ts'
import './a_todo/a_todo.ts'

import './switch/switch.ts'
import './checkbox/checkbox.ts'
import './radio/radio.ts'
import './btn/btn.ts'
import './clock/clock.ts'
import './chip/chip.ts'
import './play_btn/play_btn.ts'
import './form/form.ts'
import './search/search.ts'
import './segmented_control/segmented_control.ts'
import './icon/icon.ts'
import './slider/slider.ts'
